#! /bin/sh

sxhkd &
polybar primary &
polybar secondary &
btops &

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc rule -a feh floating=on
bspc rule -a Steam state=floating
bspc rule -a Thunar floating=on
bspc rule -a Screenkey manage=off

