#! /bin/sh

term=
code=
chrome=
steam=
empire=

bspc monitor -d $term $code $chrome $steam $empire

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc rule -a feh floating=on
bspc rule -a Steam desktop=^4 floating=on
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Terraria desktop=^5
bspc rule -a Bluetooth floating=on
bspc rule -a thunar floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
