#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)
PAD=" "

while read -r line ; do
	case $line in
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		C*)
			# clock
			clock="${line#?}"
			;;
		D*)
			# date
			date="${line#?}"
			;;
		V*)
			# volume
			volume="${line#?}"
			;;
		L*)
			# wifi
			wifi="${line#?}"
			;;
		B*)
			# battery percent output
			battery="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name="${item#?}"
				case $item in
					# M*)
					# 	# active monitor
					# 	if [ $num_mon -gt 1 ] ; then
					# 		wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
					# 	fi
					# 	;;
					# m*)
					# 	# inactive monitor
					# 	if [ $num_mon -gt 1 ] ; then
					# 		wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
					# 	fi
					# 	;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
  sys_tray='' 
  sys_tray_arr=( ${battery} ${wifi} ${volume} ${date} )
  separator=' / ' 
  #zsh arrays are 1 indexed for whatever reason
  for i in "${sys_tray_arr[@]}";
  do
    if [ -n "$i" ]; then
      sys_tray=${sys_tray}${i}${separator}
    fi
  done
  sys_tray=${sys_tray}${clock}${PAD} 
	printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${sys_tray}"
done
