#! /bin/sh
PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=30
ICON_FONT="FontAwesome:size=14"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# clock
while true;
do
	echo 'C ' $(date +"%l:%M %p");
	sleep 5;
done > "$PANEL_FIFO" &

# date
while true;
do
	echo 'D ' $(date +'%b %d')
	sleep 5
done > $PANEL_FIFO &

# volume
while true;
do
	level=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/].*//g')
	status=$(amixer get Master | tail -n 1 | cut -d '[' -f 3 | sed 's/].*//g')
	if [ $status == "on" ]; then
		echo 'V ' $level
	else
		echo 'V ' $level
	fi
	sleep 0.1
done > $PANEL_FIFO &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
