remove-empty = true
append-when-occupied = true
watch-config = true
renamers = ["classified", "client", "constant"]

[names]
constant = ""

[[names.classified]]
"" = ["Chromium", "Google-chrome-unstable"]

[[names.classified]]
"" = ["Firefox"]

[[names.classified]]
"" = ["Steam"]

[[names.classified]]
"" = ["Dolphin-emu"]

[[names.classified]]
"" = ["streamlink-twitch-gui"]

[[names.classified]]
"" = ["discord"]

[[names.classified]]
"" = ["Code"]

[[names.classified]]
"" = ["Termite", "Alacritty", "URxvt"]

[[names.classified]]
"" = ["Thunar"]
